import { FsComponent } from '@/components/fs'
import { Wallet } from '@/components/wallet'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>fs test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script async src="https://unpkg.com/isomorphic-git"></script>
        <script async src="https://unpkg.com/browserfs@beta"></script> */}
      </Head>

      <main>
        <Wallet />
        <FsComponent />
      </main>
    </>
  )
}
